### ISSUE TITLE
[+] Form submitted but the response did not match the verifier.

### ISSUE THREAD

**Issue by epasho** [Arachni/build-scripts-windows#2]
Tasos, I am having this message when i push the autologin - "[+] Form submitted but the response did not match the verifier."

Is this related to the request header? I google some but nothing that would solve my issue. 

arachni https://admin url --plugin=autologin:url=https://login url,parameters="txt_Username=test&txt_Password=123go",check="My Account" --scope-exclude-pattern=Logout

 [~] Audited 0 pages.

 [~] Duration: 00:00:17
 [~] Processed 22/22 HTTP requests.
 [~] -- 1.662 requests/second.
 [~] Processed 0/0 browser jobs.
 [~] -- 0.0 second/job.

 [~] Burst response time sum     5.453 seconds
 [~] Burst response count        3
 [~] Burst average response time 1.818 seconds
 [~] Burst average               1.662 requests/second
 [~] Timed-out requests          0
 [~] Original max concurrency    20
 [~] Throttled max concurrency   20

Also, how to i tell what the output to be and where to save it? I want it in HTML. The shell is much faster then web so i would like to get familiar with the arachni framework.

Thanks for all your help.

**Comment by Zapotek** [comment]
First of all, this tracker is for the Windows packages, not Arachni Framework issues in particular.
I'll automatically close this issue but if my suggestions don't work feel free to re-open it at the [appropriate tracker](https://github.com/Arachni/arachni/issues/).

<hr/>

The CLI will generate an `.afr` report file and by default save it in the current working dir, you can pass that file to `arachni_reporter` in oder to generate reports in different formats.

About the login issue, it's like it said, "My Account" wasn't found in the response of the login operation.
If the system should look for the verifier elsewhere you can set the check URL and check pattern via the `--session-check-url` and `--session-check-check` options.

If that's not what you need and the login should have worked the first time, you can use the `--output-debug=4` option in order to see what's going on and try to fix the problem.

If you get nowhere, you can send me the URL and credentials in private and I'll try to debug the situation.

Cheers
